# .github/workflows/daily_instagram_post.yml
# Automates daily Instagram carousel posts

name: Daily Instagram Post

on:
  schedule:
    # Run daily at 9 AM EST (14:00 UTC)
    - cron: '0 14 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  post_to_instagram:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow python-dotenv
      
      - name: Create test stories
        run: |
          python << 'EOF'
          import json
          
          # Hardcoded test stories - replace with WordPress fetch later
          stories = [
              {
                  "headline": "Economic Confidence Hits New Low Among U.S. Dentists in Q2 2025",
                  "summary": "The Q2 2025 report reveals declining confidence among dentists for the second consecutive quarter. Key concerns include tariffs and inflation."
              },
              {
                  "headline": "New AI Technology Transforms Dental Diagnostics",
                  "summary": "Revolutionary AI system shows 95% accuracy in detecting early-stage cavities, potentially changing preventive care standards."
              },
              {
                  "headline": "Study Links Oral Health to Cardiovascular Disease Prevention",
                  "summary": "Major research demonstrates strong correlation between regular dental care and reduced heart disease risk in adults over 40."
              }
          ]
          
          with open('stories.json', 'w') as f:
              json.dump(stories, f)
          
          print(f"Created {len(stories)} test stories")
          EOF
      
      - name: Generate carousel images
        run: |
          python << 'EOF'
          import json
          from instagram_carousel_generator import InstagramCarouselGenerator
          
          with open('stories.json', 'r') as f:
              stories = json.load(f)
          
          generator = InstagramCarouselGenerator()
          image_paths = generator.generate_carousel(stories)
          
          with open('image_paths.json', 'w') as f:
              json.dump(image_paths, f)
          
          print(f"Generated {len(image_paths)} carousel images")
          EOF
      
      - name: Post to Instagram
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID }}
        run: |
          python << 'EOF'
          import json
          from instagram_poster import automate_daily_post
          
          with open('stories.json', 'r') as f:
              stories = json.load(f)
          
          post_id = automate_daily_post(stories)
          
          if post_id:
              print("✅ Successfully posted to Instagram!")
          else:
              print("❌ Failed to post to Instagram")
              exit(1)
          EOF
      
      - name: Upload images as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instagram-carousel-${{ github.run_number }}
          path: instagram_posts/
          retention-days: 7
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "Instagram posting failed! Check the logs."

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Instagram post successful!"
